site_name: ducklib Documentation
repo_url: https://github.com/escape-velocity-14343/ducklib
site_url: https://escape-velocity-14343.github.io/ducklib


theme:
    menu: assets/icon.svg
    # favicon: assets/out.png
    name: material
    palette:
        - scheme: default
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
          primary: custom
          accent: custom
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
          primary: custom
          accent: custom

extra_css:
    - stylesheets/custom_css.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

validation:
    links:
        absolute_links: relative_to_docs
